### ISSUE TITLE
Misspell corrected an imported constant's name.

### ISSUE THREAD

**Issue by bnkamalesh** [golangci/misspell#10]
Misspell linter corrected a constant's name which was imported from a protobuff generated package. 
The problematic constant name `Status_STATUS_CANCELLED`, was corrected to a single L. This broke our CI as well, because `autofix: true` is the default setting. 

Ref: 
https://github.com/microsoft/vscode/issues/200638
https://github.com/golang/vscode-go/issues/3087

Below I have provided the configuration of misspell.
```yaml
  misspell:
    locale: US
    ignore-words:
      - cancelled // added this now as a work around
```

p.s: I added the respective word as a config under `ignore-words` _as a work around_.
