### ISSUE TITLE
Use Go wiki rules

### ISSUE THREAD

**Issue by AlekSi** [golangci/misspell#11]
It would be nice if this linter reported, for example, "marshalling" (double ell) as incorrect spelling. See https://go.dev/wiki/Spelling

**Comment by ldez** [comment]
The following typos are already detected:
- cancelled
- marshalling
- canceling
- marshalled

Only the following typos are not detected:
- iff
- cancelation

To use US dictionary:
```bash
misspell -locale=US
```
or
```yml
linters-settings:
  misspell:
    locale: US
```
